.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: 'puppet-module-win-system-r#{minor_version}'
        platforms:
          - mswin
          - mingw
          - x64_mingw
      - gem: 'puppet_litmus'
        platforms:
          - ruby
          - mswin
          - mingw
          - x64_mingw
        condition: "ENV['PUPPET_GEM_VERSION'].nil? or ENV['PUPPET_GEM_VERSION'] !~ %r{ 5}"

Rakefile:
  requires:
  use_litmus_tasks: true

.travis.yml:
  secure: "G875icL7Rrt+u7EA5dCqSK/mVVZJRb6q46o+8iqiOxnFVHjbvKBboGzPqSYnGwKZQ89nr1//yGLjmjQ9TbGGIu6BU50XduPm9fmAJubjj7fDY7e6T6G6M/nyORpgSMdTiYFvBA7pqHWVkM4HGze/VdBSQYcEYG3HiKUSkjk234I3UabyxEFMlxHvEwWSs2Z5RtZBpR4bz/CCEE+ZGdF3cjaSyWH9YURgWgy7CSV6kvhoGXDm/nMpB31qlZUwlns7H15T5LDShugKa7+3+ubZBxVWQBDM8/xAETcHdm+UdjFt5pUbI4/EfGdeGRIEwmh32Ajah65/akMobyhT1ywaswxKPXhJX4x1xq7c+ay7wc3L9sxyulrQfT2RrHbRTs7KgZGIvV4+Z1k7UQ6AtHcGgVPGd8cu+OdszZxUO14wKE12+AXEKf78d6oyEJ4OCnQyC56e+mW+6V+iOFY+laYp5HPNhCcx9s1P6MCTCg6LrZ2JA5tbDij7yai0hbApxM5g0T/vPqU49ng//2SQ+w7D/XxFKYYpPRJQmul8djU9F4ztw8Hf3J39W1O4+0cvjppiHO7MKtSo61xKl28dFwL3bfulK2JCvuU34PvHCxOaUJ7OSqQatZ8i++QD6wSJkK7kOsS2OVAJjPmYru2wp3i/pPMYOY4Y4ttxZ5ugCrp0R7c="