---
# This file is used by the Splunk container to configure settings that would
# typically be set in the web interface. 
# https://splunk.github.io/docker-splunk/ADVANCED.html
retry_num: 100
splunk:
  opt: /opt
  home: /opt/splunk
  user: splunk
  group: splunk
  exec: /opt/splunk/bin/splunk
  pid: /opt/splunk/var/run/splunk/splunkd.pid
  password: "{{ splunk_password | default(<password>) }}"
  svc_port: 8089
  s2s_port: 9997
  http_port: 8000
  hec:
    enable: True
    ssl: False
    port: 8088
    token: abcd1234
  smartstore: null
